### ISSUE TITLE
Release 0.1?

### ISSUE THREAD

**Issue by zoidbergwill** [dart-lang/py-gfm#14]
Things seem to have come a long way from the version 0.0.2 on PyPI. 

Is 0.1 ready for release?

**Comment by chriskrycho** [comment]
Did this ever happen? I'd like it as well. I can of course use it locally; it'd just be nice to be able to use it via `pip` for `virtualenv` setups.

**Comment by zoidbergwill** [comment]
Hopefully this is enough interest.
